name: Run Example

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run python-test-runner on example files
      run: sh run-in-docker.sh example test/
    - name: Verify that results.json is created
      run: test -f test/results.json && cat test/results.json
